In [21]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [22]:
df  = pd.read_csv("Telco-Customer-Churn.csv")
df.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   
3  7795-CFOCW    Male              0      No         No      45           No   
4  9237-HQITU  Female              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   
3  No phone service             DSL            Yes  ...              Yes   
4                No     Fiber optic             No  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   
3         Yes          No              No        One year               No   
4          No          No              No  Month-to-month              Yes   

               PaymentMethod MonthlyCharges  TotalCharges Churn  
0           Electronic check          29.85         29.85    No  
1               Mailed check          56.95        1889.5    No  
2               Mailed check          53.85        108.15   Yes  
3  Bank transfer (automatic)          42.30       1840.75    No  
4           Electronic check          70.70        151.65   Yes  

[5 rows x 21 columns]

In [23]:
df.shape

(7043, 21)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   str    
 1   gender            7043 non-null   str    
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   str    
 4   Dependents        7043 non-null   str    
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   str    
 7   MultipleLines     7043 non-null   str    
 8   InternetService   7043 non-null   str    
 9   OnlineSecurity    7043 non-null   str    
 10  OnlineBackup      7043 non-null   str    
 11  DeviceProtection  7043 non-null   str    
 12  TechSupport       7043 non-null   str    
 13  StreamingTV       7043 non-null   str    
 14  StreamingMovies   7043 non-null   str    
 15  Contract          7043 non-null   str    
 16  PaperlessBilling  7043 non-null   str    
 17  Paymen

In [25]:
df.isna().sum().sort_values(ascending=False)

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

1. Basic cleaning (missing, encoding, etc.)

2. Statistical filtering
   - Mutual Information
   - Random Forest importance
   - Permutation importance

3. Top 10–15 features select karo

4. Inka quick visualization
   - Boxplot
   - Histogram

5. Model training
   - Baseline (all features)
   - Selected features

6. Compare performance


In [26]:
# Drop ID column
df = df.drop("customerID", axis=1)

# Encode categorical features
df_new = pd.get_dummies(df, drop_first=True)
df_new.head()

SeniorCitizen  tenure  MonthlyCharges  gender_Male  Partner_Yes  \
0              0       1           29.85        False         True   
1              0      34           56.95         True        False   
2              0       2           53.85         True        False   
3              0      45           42.30         True        False   
4              0       2           70.70        False        False   

   Dependents_Yes  PhoneService_Yes  MultipleLines_No phone service  \
0           False             False                            True   
1           False              True                           False   
2           False              True                           False   
3           False             False                            True   
4           False              True                           False   

   MultipleLines_Yes  InternetService_Fiber optic  ...  TotalCharges_996.45  \
0              False                        False  ...                False   
1              False                        False  ...                False   
2              False                        False  ...                False   
3              False                        False  ...                False   
4              False                         True  ...                False   

   TotalCharges_996.85  TotalCharges_996.95  TotalCharges_997.65  \
0                False                False                False   
1                False                False                False   
2                False                False                False   
3                False                False                False   
4                False                False                False   

   TotalCharges_997.75  TotalCharges_998.1  TotalCharges_999.45  \
0                False               False                False   
1                False               False                False   
2                False               False                False   
3                False               False                False   
4                False               False                False   

   TotalCharges_999.8  TotalCharges_999.9  Churn_Yes  
0               False               False      False  
1               False               False      False  
2               False               False       True  
3               False               False      False  
4               False               False       True  

[5 rows x 6560 columns]

In [ ]:
from sklearn.feature_selection import mutual_info_classif
import pandas as pd

X = df_new.drop( "Churn_Yes", axis=1)
y = df_new["Churn_Yes"]

mi = mutual_info_classif(X, y)

mi_series = pd.Series(mi, index=X.columns)



tenure                            0.079696
Contract_Two year                 0.058527
PaymentMethod_Electronic check    0.051190
MonthlyCharges                    0.048231
InternetService_Fiber optic       0.045068
                                    ...   
TotalCharges_4828.05              0.000000
TotalCharges_4822.85              0.000000
TotalCharges_4820.55              0.000000
TotalCharges_4820.15              0.000000
TotalCharges_48.55                0.000000
Length: 6559, dtype: float64

In [30]:
mi_series = pd.Series(mi, index=X.columns)

In [31]:
top_features = mi_series.sort_values(ascending=False).head(10).index

In [32]:
top_features

Index(['tenure', 'Contract_Two year', 'PaymentMethod_Electronic check',
       'MonthlyCharges', 'InternetService_Fiber optic',
       'StreamingTV_No internet service',
       'DeviceProtection_No internet service',
       'StreamingMovies_No internet service',
       'TechSupport_No internet service',
       'OnlineSecurity_No internet service'],
      dtype='str')

In [34]:
# removing repeated features
top_features = top_features.drop(["DeviceProtection_No internet service", "StreamingMovies_No internet service", "OnlineSecurity_No internet service"])

In [35]:
top_features

Index(['tenure', 'Contract_Two year', 'PaymentMethod_Electronic check',
       'MonthlyCharges', 'InternetService_Fiber optic',
       'StreamingTV_No internet service', 'TechSupport_No internet service'],
      dtype='str')

In [36]:
from sklearn.model_selection import train_test_split
X_sel = X[top_features]
X_train, X_test, y_train, y_test = train_test_split(X_sel, y, test_size=0.2, random_state=42)

In [37]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [38]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7530163236337828
              precision    recall  f1-score   support

       False       0.82      0.85      0.84      1036
        True       0.54      0.48      0.51       373

    accuracy                           0.75      1409
   macro avg       0.68      0.66      0.67      1409
weighted avg       0.74      0.75      0.75      1409

[[883 153]
 [195 178]]


In [39]:
model = RandomForestClassifier(class_weight="balanced")
model.fit(X_train, y_train)


RandomForestClassifier(class_weight='balanced')

In [40]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7530163236337828
              precision    recall  f1-score   support

       False       0.82      0.85      0.84      1036
        True       0.54      0.47      0.50       373

    accuracy                           0.75      1409
   macro avg       0.68      0.66      0.67      1409
weighted avg       0.74      0.75      0.75      1409

[[884 152]
 [196 177]]


In [42]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(class_weight="balanced", max_iter=1000)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [43]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7416607523066004
              precision    recall  f1-score   support

       False       0.91      0.72      0.80      1036
        True       0.51      0.82      0.63       373

    accuracy                           0.74      1409
   macro avg       0.71      0.77      0.71      1409
weighted avg       0.81      0.74      0.76      1409

[[741 295]
 [ 69 304]]


In [44]:
rf = RandomForestClassifier(
    class_weight="balanced",
    n_estimators=300,
    max_depth=6,
    random_state=42
)

rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.751596877217885
              precision    recall  f1-score   support

       False       0.93      0.72      0.81      1036
        True       0.52      0.85      0.64       373

    accuracy                           0.75      1409
   macro avg       0.72      0.78      0.73      1409
weighted avg       0.82      0.75      0.77      1409

[[742 294]
 [ 56 317]]


In [45]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", LogisticRegression(class_weight="balanced"))
])

model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.7409510290986515
              precision    recall  f1-score   support

       False       0.91      0.71      0.80      1036
        True       0.51      0.82      0.62       373

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.81      0.74      0.76      1409

[[740 296]
 [ 69 304]]


In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "clf__C": [0.01, 0.1, 1, 10, 100]
}

grid = GridSearchCV(model, param_grid, scoring="f1", cv=5)
grid.fit(X_train, y_train)

print(grid.best_params_)


{'clf__C': 100}


In [47]:
y_pred = grid.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7409510290986515
              precision    recall  f1-score   support

       False       0.91      0.71      0.80      1036
        True       0.51      0.82      0.62       373

    accuracy                           0.74      1409
   macro avg       0.71      0.76      0.71      1409
weighted avg       0.81      0.74      0.76      1409

[[740 296]
 [ 69 304]]


In [49]:
from sklearn.inspection import permutation_importance

result = permutation_importance(model, X_sel, y, n_repeats=10, random_state=42)

perm_imp = pd.Series(result.importances_mean, index=X_sel.columns)
perm_imp.sort_values(ascending=False)

tenure                             0.066321
InternetService_Fiber optic        0.035099
PaymentMethod_Electronic check     0.004274
MonthlyCharges                     0.001093
StreamingTV_No internet service   -0.005197
TechSupport_No internet service   -0.005197
Contract_Two year                 -0.006191
dtype: float64

In [50]:
top_features

Index(['tenure', 'Contract_Two year', 'PaymentMethod_Electronic check',
       'MonthlyCharges', 'InternetService_Fiber optic',
       'StreamingTV_No internet service', 'TechSupport_No internet service'],
      dtype='str')

In [52]:
final_features = top_features[:4]
final_features

Index(['tenure', 'Contract_Two year', 'PaymentMethod_Electronic check',
       'MonthlyCharges'],
      dtype='str')

In [53]:
X_sel = X[final_features]
X_train, X_test, y_train, y_test = train_test_split(X_sel, y, test_size=0.2, random_state=42)


In [54]:
rf = RandomForestClassifier(
    class_weight="balanced",
    n_estimators=300,
    max_depth=6,
    random_state=42
)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.7572746628814763
              precision    recall  f1-score   support

       False       0.92      0.73      0.82      1036
        True       0.53      0.83      0.64       373

    accuracy                           0.76      1409
   macro avg       0.72      0.78      0.73      1409
weighted avg       0.82      0.76      0.77      1409

[[758 278]
 [ 64 309]]
